//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inclusion_sports.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Map
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pcode { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00000000}")]
        public Nullable<decimal> Latitude { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00000000}")]
        public Nullable<decimal> Longitude { get; set; }
        public string Address { get; set; }
        public string Sports { get; set; }
        public string Diversity { get; set; }
        public string Link { get; set; }
    }
}
