//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inclusion_sports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TobaccoHomo
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public int Y2010 { get; set; }
        public int Y2013 { get; set; }
        public int Y2016 { get; set; }
        public int Y2019 { get; set; }
    }
}
